# Generated by Django 5.0.3 on 2024-05-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Universidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestre',
            name='Fin',
            field=models.DateField(default='2000-10-03'),
        ),
        migrations.AddField(
            model_name='semestre',
            name='Inicio',
            field=models.DateField(default='2000-10-03'),
        ),
    ]
