# Generated by Django 5.0.3 on 2024-05-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Universidad', '0002_semestre_fin_semestre_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='Fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='Inicio',
            field=models.DateField(),
        ),
    ]
