# Generated by Django 5.0.3 on 2024-05-29 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Universidad', '0003_alter_semestre_fin_alter_semestre_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=35)),
                ('Cantidad_Notas', models.IntegerField()),
                ('Creditos', models.IntegerField()),
                ('Semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Universidad.semestre')),
            ],
        ),
    ]
