# Generated by Django 5.0.3 on 2024-05-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Universidad', '0004_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='Minimo_A',
            field=models.IntegerField(default=0),
        ),
    ]
