# Generated by Django 5.0.3 on 2024-05-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Universidad', '0005_materia_minimo_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='Minimo_A',
            field=models.IntegerField(),
        ),
    ]
