# Generated by Django 5.0.3 on 2024-05-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Universidad', '0007_dias_horario_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='Descripcion',
            field=models.CharField(default='Void', max_length=50),
        ),
    ]
