# Generated by Django 5.0.3 on 2024-05-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Universidad', '0008_nota_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='Descripcion',
            field=models.CharField(max_length=50),
        ),
    ]
